name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.TOKEN }}
          base: header, repositories , activity
          plugin_habits : yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: asia/taipei
          
