name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: language.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          template: repository
          repo: metrics
          user: lowlighter
          plugin_languages: yes
      - uses: lowlighter/metrics@master
        with:
          filename: repository.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          template: repository
          repo: metrics
          user: lowlighter
          
          
